name: Start Bot
on:
  workflow_dispatch: # للتشغيل اليدوي الآن للتجربة
  schedule:
    - cron: '0 10 * * *' # يعمل تلقائياً كل يوم الساعة 10 صباحاً

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Script
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        run: python main.py
        
