name: Viral AI Video Creator
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *' # 10 صباحاً بتوقيت مكة/اليمن

jobs:
  create-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install System Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Install Libraries
        run: |
          pip install -r requirements.txt

      - name: Run AI Bot
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        run: python main.py
