name: BuzzShorts YouTube Uploader

on:
  workflow_dispatch: # للتشغيل اليدوي بضغطة زر

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          # هذا الرابط الصحيح بناءً على بياناتك
          workload_identity_provider: 'projects/2248768852/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          # الإيميل المتوقع بناءً على اسم مشروعك
          service_account: 'buzz-shorts@buzz-shorts.iam.gserviceaccount.com'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2 moviepy==1.0.3

      - name: Run BuzzShorts Script
        run: python main.py
        
