name: Viral AI Video Creator
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

permissions:
  contents: write

jobs:
  create-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          # هذا السطر يحل مشكلة الأمان في التوزيعات الجديدة
          sudo sed -i 's/domain="path" rights="none" pattern="@\*"/domain="path" rights="read|write" pattern="@\*"/g' /etc/ImageMagick-6/policy.xml

      - name: Install Libraries
        run: |
          pip install --upgrade pip
          pip install moviepy google-api-python-client google-auth-oauthlib requests Pillow

      - name: Run AI Bot
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        run: python main.py
        
